package com.javainterview.interviewhub.enums;

public enum Topic {

    // Java Core
    OOP,
    STRINGS,
    COLLECTIONS,
    GENERICS,
    EXCEPTIONS,
    STREAMS_AND_LAMBDAS,
    MULTITHREADING,
    JVM_AND_MEMORY,
    JAVA_MODERN_FEATURES,
    SOLID,
    DESIGN_PATTERNS,

    // Spring Boot
    SPRING_CORE,
    SPRING_BOOT,
    SPRING_MVC,
    SPRING_SECURITY,
    SPRING_DATA_JPA,
    SPRING_TESTING,
    SPRING_ACTUATOR,

    // SQL & Databases
    SQL_BASICS,
    JOINS,
    TRANSACTIONS,
    INDEXES,
    QUERY_OPTIMIZATION,
    POSTGRESQL,

    // Hibernate / JPA
    JPA_ENTITIES,
    ENTITY_RELATIONSHIPS,
    FETCHING,
    CASCADE,
    PERSISTENCE_CONTEXT,
    N_PLUS_ONE,
    HIBERNATE_TRANSACTIONS,

    // REST APIs
    HTTP_BASICS,
    REST_API,
    HTTP_STATUS_CODES,
    API_VALIDATION,
    API_SECURITY,
    API_VERSIONING,
    ERROR_HANDLING,

    // Microservices
    MICROSERVICES,
    SERVICE_COMMUNICATION,
    API_GATEWAY,
    SERVICE_DISCOVERY,
    RESILIENCE,
    DISTRIBUTED_TRANSACTIONS,
    OBSERVABILITY,
    SYSTEM_DESIGN,

    // Docker
    DOCKER_BASICS,
    DOCKERFILE,
    DOCKER_COMPOSE,
    DOCKER_NETWORKING,
    DOCKER_VOLUMES,
    DOCKER_DEPLOYMENT,

    // Kafka
    KAFKA_BASICS,
    KAFKA_PRODUCERS,
    KAFKA_CONSUMERS,
    KAFKA_PARTITIONS,
    CONSUMER_GROUPS,
    OFFSETS,
    DELIVERY_SEMANTICS,
    KAFKA_ERROR_HANDLING,

    // Camunda
    CAMUNDA_7,
    CAMUNDA_8,
    CAMUNDA_7_VS_8,
    BPMN,
    PROCESS_VARIABLES,
    EXTERNAL_TASKS,
    JOB_WORKERS,
    MESSAGE_CORRELATION,

    // Legacy values kept temporarily
    DOCKER,
    KAFKA,
    CAMUNDA,

    // General
    GIT,
    UNIT_TESTING,
    INTEGRATION_TESTING,
    GENERAL
}